#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Naoto Sato
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

for line in sys.stdin:
    line = line.rstrip()

print(ans)
